name: Node CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone page repository
      uses: actions/checkout@v2
      with:        
        repository: augustbright/augustbright.github.io
        ref: master
        token: ${{secrets.page_repo_token}}
        path: ./page
    - run: | 
        cd page 
        git config --global user.email "vtumanov782@gmail.com"
        git config --global user.name "Github Action"

        git commit -m "empty" --allow-empty 
        git push origin


    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run deploy
      env:
        CI: true