name: Node CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run deploy
      env:
        CI: true
    - name: Clone page repository
      uses: actions/checkout@v2
      with:        
        repository: augustbright/augustbright.github.io
        ref: master
        token: ${{secrets.page_repo_token}}
        path: ./page
    - name: Cleaning up page directory
        working-directory: ./page
        run: |
          shopt -s extglob
          rm -rf !(.git)
    - name: Copying new files to page repository
      run: cp -a ./out/. ./page/
    - name: Pushing changes to page repository
      working-directory: ./page
      run: |
          git config --global user.email "vtumanov782@gmail.com"
          git config --global user.name "Github Action"
          git commit -a -m "Auto push by github action" --allow-empty
          git push origin master
  